### ISSUE TITLE
Add intro?

### ISSUE THREAD

**Issue by GarySiu** [vendethiel/trying.apl#23]
The tables are completely unreadable on mobile. Do you think you can throw a one paragraph description on the top of the readme to encourage people to link the repo?

**Comment by vendethiel** [comment]
I'm not sure why you want to use the repo on mobile? It seems pretty hard to type characters.

I think the main interest of this repo is to run the files with the file source on the side so you can see what's produced.
What would such a description look like?

**Comment by GarySiu** [comment]
Just a couple of lines so someone would know what they're looking at? "A collection of APL code examples with comments. Because APL is awesome." Got linked via Reddit while browsing on mobile and wasn't sure if it was worth bookmarking for later because no context. Just a thought! You can leave it if you prefer.
