### ISSUE TITLE
Promote APL language development

### ISSUE THREAD

**Issue by ShionAt** [vendethiel/trying.apl#24]
ShionKeys to promote / change the computer civilization born, he can promote the development of APL, APL is no longer limited by the keyboard

**Comment by vendethiel** [comment]
I use the vim-apl mode, but thanks for the info.

**Comment by ShionAt** [comment]
Do not rush to delete you should let more APL developers see ShionKeys

**Comment by ShionAt** [comment]
fixes #24

**Comment by ShionAt** [comment]
fix #24

**Comment by ShionAt** [comment]
fix #24
